" Plugin manager https://github.com/junegunn/vim-plug
"
" Run
" :PlugInstall to install new plugins
" :PlugStatus to view plugin status
"
" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" Shorthand notation fetches https://github.com/jamessan/vim-gnupg
Plug 'jamessan/vim-gnupg'

Plug 'altercation/vim-colors-solarized'

Plug 'plasticboy/vim-markdown'

" Tab variable completion
Plug 'ervandew/supertab'

" Syntax checking with many plugins
Plug 'vim-syntastic/syntastic'

" JSON-specific mode rather than the default javascript mode
Plug 'elzr/vim-json'

call plug#end()

" Detect the system name for customizations
let s:uname=substitute(system('uname'), '\n', '', '')

" Better colors for a dark/light background
if has('gui_running')
    set background=light
    set lines=40 columns=100
else
    set background=light
endif

" --------------------------------------------------------------------------------
" Solarized color scheme: http://ethanschoonover.com/solarized
"
" Option for low contrast
" let g:solarized_contrast="high"
"
" Variables that may need to be set for the solarized color palette. Enable this in OSX terminal when
" using Solarized color scheme. Disable it in Konsole or the background is yellowish.
if s:uname == "Darwin"
    let g:solarized_termcolors=256
endif

" May need to set this if the terminal only supports 256 colors (especially in light mode)
set t_Co=256
colorscheme solarized

" --------------------------------------------------------------------------------
" General options

" Syntax hilighting on
syntax enable

" Show line numbers (can't cut and paste in the terminal)
" set number

" Indent 4 spaces per indent and Use spaces for indentation
set tabstop=4
set shiftwidth=4
set expandtab

" Shortcut for toggling paste mode (disabling auto-indent when pasting)
set pastetoggle=<F3>

" Indent relative to current line
" set autoindent
" set cindent
" Don't automatically continue comments on the next line
" set formatoptions-=c formatoptions-=r formatoptions-=o

" Some plugins (e.g., filetype plugins) are loaded after the .vimrc file and overwrite
" options defined here. Automatically re-apply formatting options when any file is loaded.
" We can apply it to all filetypes or whenever a new file is read.
" Note that formatoptions-=cro does not work.
"
" Running ':verb set fo' will show you where an option was last set
" Running :set <option>? will display the options current value
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o foldmethod=manual

" Show matching braces
set showmatch

" Show line/column information
set ruler

" Disable beeps
set vb t_vb=

" Do not hilight search fields
set nohls

" Force vim to reset the terminal and clear the color scheme.
" See http://vimdoc.sourceforge.net/htmldoc/autocmd.html
" See http://superuser.com/questions/942597/why-does-my-vim-colorscheme-stay-after-i-close-vim
autocmd VimLeave * printf '\e[0m'

" --------------------------------------------------------------------------------
" Syntastic configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" See https://github.com/vim-syntastic/syntastic/blob/master/doc/syntastic-checkers.txt
" Note that only the part after 'syntastic-javascript-' is needed

" Requires jsonlint to be installed and in the path. See https://jsonlint.com/ or 'npm install jsonlint'
let g:syntastic_json_checkers = ['jsonlint']
" Requires phpcs to be installed and in the path. See https://github.com/squizlabs/PHP_CodeSniffer
let g:syntastic_php_checkers = ['phpcs']
